### ISSUE TITLE
Add compatibility to Django 2.0+

### ISSUE THREAD

**Issue by NotAndrewFields** [MattBroach/Django-Merged-Inlines#6]
I just feel alot of the people would want a really customizable inline but most of them are already updated to Django 2.1, like myself. I will try to help with :100:% of my time.

**Comment by MattBroach** [comment]
Hey @NotAndrewFields, sorry for a long delay in my reply.  I finally had some spare moments to look into this, and I couldn't find any compatibility issues with Django 2.0 or 2.1.  Now, some of the tests were broken due to changes to URLs, and I updated the tests to better reflect the current Django needs -- but the core library was actually untouched.  If you are or were experiencing problems using this library with Django 2.0, please let me know (preferably with code samples and/or tracebacks).  

Closing for now, but feel free to re-open if you're having issues.
